<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Disease;

class DiseaseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $diseases = [
            [
                'name' => 'Apple___Apple_scab',
                'description' => 'A fungal disease caused by Venturia inaequalis that affects apple trees. It creates olive-green to black spots on leaves and fruit.',
                'scientific_details' => 'Apple scab (Venturia inaequalis) is one of the most serious diseases of apple worldwide. The fungus overwinters in fallen leaves and produces ascospores in spring that are released during rain events. Primary infection occurs on young leaves and developing fruit, with secondary infections continuing throughout the growing season. The disease cycle is heavily dependent on temperature and leaf wetness duration.',
                'treatment_suggestions' => 'Apply fungicides early in the season. Remove and destroy fallen leaves. Prune trees to improve air circulation. Plant resistant apple varieties.',
                'prevention_methods' => 'Plant resistant cultivars like Liberty, Enterprise, or GoldRush. Maintain proper tree spacing for good air circulation. Apply dormant sprays in late winter. Rake and destroy fallen leaves in autumn. Use preventative fungicide program starting at green tip stage.',
                'required_tools' => 'Pruning shears, rake, fungicide sprayer, protective gear (gloves, mask, goggles), sanitizing solution for tools.',
                'environmental_factors' => 'Wet spring conditions promote disease development. Requires 6-9 hours of leaf wetness at 61-75°F (16-24°C) for infection. High humidity and poor air circulation increase disease severity.',
                'severity_level' => 'High',
                'average_treatment_time' => 3.5,
                'plant_type' => 'Apple',
                'seasonal_prevalence' => json_encode(['Spring' => 'High', 'Summer' => 'Moderate', 'Fall' => 'Low', 'Winter' => 'None']),
                'statistics' => json_encode([
                    'infection_rate' => '70% of untreated orchards',
                    'yield_impact' => 'Up to 70% reduction in marketable fruit',
                    'treatment_success_rate' => '85% with proper management',
                    'common_regions' => ['Northeast US', 'Midwest US', 'Northern Europe', 'Temperate Asia']
                ]),
                'source_url' => 'https://extension.umn.edu/plant-diseases/apple-scab',
            ],
            [
                'name' => 'Apple___Black_rot',
                'description' => 'A fungal disease caused by Botryosphaeria obtusa that affects apple trees. It causes leaf spots, fruit rot, and cankers on branches.',
                'scientific_details' => 'Black rot is caused by the fungus Botryosphaeria obtusa (syn. Diplodia seriata). The pathogen can infect leaves, fruit, and woody tissues, causing frogeye leaf spot, fruit rot, and limb cankers. The fungus overwinters in cankers, mummified fruit, and dead wood. Spores are released during warm, wet periods and can infect throughout the growing season. The disease is particularly damaging in humid regions.',
                'treatment_suggestions' => 'Prune out dead or diseased wood. Remove mummified fruit. Apply fungicides during the growing season. Maintain good orchard sanitation.',
                'prevention_methods' => 'Remove cankers by cutting at least 15 inches below visible infection. Eliminate fire-blighted branches which can be entry points. Apply protective fungicides from pink bud stage through harvest. Remove mummified fruit and dead wood during winter pruning.',
                'required_tools' => 'Sharp pruning shears, pruning saw, wound dressing, fungicide sprayer, orchard sanitation tools, protective gear.',
                'environmental_factors' => 'Warm temperatures (75-80°F/24-27°C) and high humidity favor disease development. Wounds from hail, insects, or mechanical damage provide entry points for the pathogen.',
                'severity_level' => 'Moderate to High',
                'average_treatment_time' => 2.5,
                'plant_type' => 'Apple',
                'seasonal_prevalence' => json_encode(['Spring' => 'Moderate', 'Summer' => 'High', 'Fall' => 'Moderate', 'Winter' => 'Low']),
                'statistics' => json_encode([
                    'infection_rate' => '40-60% in susceptible orchards',
                    'yield_impact' => 'Up to 50% reduction in marketable fruit',
                    'treatment_success_rate' => '75% with integrated management',
                    'common_regions' => ['Eastern US', 'Midwest US', 'Southern Europe', 'Australia']
                ]),
                'source_url' => 'https://extension.umn.edu/plant-diseases/black-rot-apple',
            ],
            [
                'name' => 'Apple___Cedar_apple_rust',
                'description' => 'A fungal disease caused by Gymnosporangium juniperi-virginianae that requires both apple trees and cedar trees to complete its life cycle. It causes bright orange-yellow spots on apple leaves and fruit.',
                'scientific_details' => 'Cedar apple rust is caused by Gymnosporangium juniperi-virginianae, a heteroecious fungus requiring two hosts to complete its life cycle: apple (Malus) and eastern red cedar or juniper (Juniperus). The fungus produces distinctive orange gelatinous telial horns on cedar galls during spring rains. Basidiospores from these structures infect apple trees, while aeciospores produced on apple leaves and fruit later infect cedar trees. The complex life cycle makes this disease particularly challenging to manage.',
                'treatment_suggestions' => 'Plant resistant varieties. Remove nearby cedar trees if possible. Apply fungicides in spring. Maintain good air circulation around trees.',
                'prevention_methods' => 'Plant resistant apple cultivars like Liberty, Enterprise, or Williams Pride. Remove eastern red cedars within a 1/4 mile radius if possible. Apply protective fungicides from pink bud stage through petal fall. Improve air circulation through proper pruning.',
                'required_tools' => 'Fungicide sprayer, pruning tools, tree identification guide for cedar removal, protective gear, distance measuring tools.',
                'environmental_factors' => 'Spring rains trigger spore release from cedar galls. Mild temperatures (50-75°F/10-24°C) favor infection. Disease severity correlates with proximity to cedar trees and spring rainfall patterns.',
                'severity_level' => 'Moderate',
                'average_treatment_time' => 2.0,
                'plant_type' => 'Apple',
                'seasonal_prevalence' => json_encode(['Spring' => 'Very High', 'Summer' => 'Low', 'Fall' => 'Very Low', 'Winter' => 'None']),
                'statistics' => json_encode([
                    'infection_rate' => '30-80% depending on cedar proximity',
                    'yield_impact' => '20-40% reduction in fruit quality',
                    'treatment_success_rate' => '70% with combined approaches',
                    'common_regions' => ['Eastern US', 'Midwest US', 'Parts of Canada']
                ]),
                'source_url' => 'https://extension.umn.edu/plant-diseases/cedar-apple-rust',
            ],
            [
                'name' => 'Apple___healthy',
                'description' => 'The plant appears healthy with no visible signs of disease or pest damage.',
                'scientific_details' => 'Healthy apple trees (Malus domestica) display vibrant foliage, robust growth patterns, and proper fruit development. Leaves should be uniformly green, firm, and free of spots or abnormal coloration. Branches should show appropriate annual growth with no cankers or lesions. Fruit development follows a predictable pattern from blossom to harvest, with skin clear of blemishes, rot, or irregular coloration.',
                'treatment_suggestions' => 'Continue regular maintenance including proper watering, fertilization, and pruning practices.',
                'prevention_methods' => 'Maintain balanced nutrition with annual soil testing. Follow a preventative spray schedule appropriate for your region. Prune annually during dormancy to maintain tree structure and air flow. Monitor for pests regularly with traps or visual inspection. Maintain proper irrigation, avoiding overhead watering.',
                'required_tools' => 'Pruning shears, loppers, pruning saw, soil testing kit, sprayer for preventative treatments, irrigation equipment, mulch.',
                'environmental_factors' => 'Apple trees thrive in full sun (6+ hours daily) and well-drained soil with pH 6.0-7.0. Require 800-1,600 chill hours depending on variety. Optimal growing temperature range is 60-75°F (15-24°C).',
                'severity_level' => 'None',
                'average_treatment_time' => 0.0,
                'plant_type' => 'Apple',
                'seasonal_prevalence' => json_encode(['Spring' => 'N/A', 'Summer' => 'N/A', 'Fall' => 'N/A', 'Winter' => 'N/A']),
                'statistics' => json_encode([
                    'productivity' => 'Average yield 100-200 fruits per mature tree',
                    'lifespan' => '35-45 years for standard trees, 15-25 for dwarf varieties',
                    'pollination_requirements' => 'Most varieties require cross-pollination',
                    'common_varieties' => ['Honeycrisp', 'Gala', 'Fuji', 'Granny Smith', 'Red Delicious']
                ]),
                'source_url' => null,
            ],
            [
                'name' => 'Blueberry___healthy',
                'description' => 'The blueberry plant appears healthy with no visible signs of disease or pest damage.',
                'scientific_details' => 'Healthy blueberry plants (Vaccinium spp.) exhibit specific characteristics including vibrant green leaves (or seasonal red/purple in fall), firm stems with proper lignification, and uniform berry development. The root system is fibrous and shallow, forming a symbiotic relationship with mycorrhizal fungi. Plant health is heavily dependent on soil acidity, with optimal pH between 4.5-5.5 for proper nutrient uptake, particularly iron.',
                'treatment_suggestions' => 'Maintain acidic soil pH (4.5-5.5). Provide adequate water and mulch. Prune annually to remove old wood.',
                'prevention_methods' => 'Test soil pH annually and amend with sulfur if needed. Apply 2-4 inches of organic mulch like pine needles or sawdust. Prune to remove oldest canes (typically 20% of bush) during dormancy. Ensure consistent moisture with drip irrigation. Apply balanced fertilizer formulated for acid-loving plants.',
                'required_tools' => 'Soil pH tester, pruning shears, acidic mulch materials, drip irrigation system, fertilizer for acid-loving plants, bird netting.',
                'environmental_factors' => 'Requires acidic soil (pH 4.5-5.5), consistent moisture but not waterlogged conditions, full sun to partial shade depending on climate, and winter chilling hours (varies by variety, typically 200-800 hours below 45°F/7°C).',
                'severity_level' => 'None',
                'average_treatment_time' => 0.0,
                'plant_type' => 'Blueberry',
                'seasonal_prevalence' => json_encode(['Spring' => 'N/A', 'Summer' => 'N/A', 'Fall' => 'N/A', 'Winter' => 'N/A']),
                'statistics' => json_encode([
                    'productivity' => '5-20 pounds per mature bush depending on variety',
                    'lifespan' => '40-50 years with proper care',
                    'establishment_period' => '3-4 years to full production',
                    'common_varieties' => ['Highbush', 'Lowbush', 'Rabbiteye', 'Half-high']
                ]),
                'source_url' => null,
            ],
            [
                'name' => 'Cherry_(including_sour)___Powdery_mildew',
                'description' => 'A fungal disease caused by Podosphaera clandestina that affects cherry trees. It appears as a white powdery coating on leaves and sometimes fruit.',
                'scientific_details' => 'Powdery mildew on cherry is primarily caused by Podosphaera clandestina (formerly Sphaerotheca pannosa), an obligate parasite that grows on the surface of plant tissues. Unlike many fungal pathogens, it does not require free water for infection but thrives in high humidity. The fungus produces haustoria that penetrate host cells to extract nutrients. Spores are wind-dispersed and can germinate at relative humidity as low as 70%, making this disease particularly persistent.',
                'treatment_suggestions' => 'Apply fungicides at first sign of disease. Prune to improve air circulation. Remove and destroy infected plant parts.',
                'prevention_methods' => 'Plant resistant varieties when available. Maintain proper tree spacing and prune to enhance air circulation. Apply preventative fungicides at early leaf development. Avoid excessive nitrogen fertilization which promotes susceptible succulent growth. Remove infected leaves and shoots promptly.',
                'required_tools' => 'Pruning shears, fungicide sprayer, protective gear, sanitizing solution for tools, proper disposal containers for infected material.',
                'environmental_factors' => 'Temperatures between 60-80°F (15-27°C) favor disease development. High humidity promotes infection, but unlike many fungi, free water inhibits spore germination. Shade and poor air circulation increase disease severity.',
                'severity_level' => 'Moderate',
                'average_treatment_time' => 2.0,
                'plant_type' => 'Cherry',
                'seasonal_prevalence' => json_encode(['Spring' => 'Moderate', 'Summer' => 'High', 'Fall' => 'Moderate', 'Winter' => 'None']),
                'statistics' => json_encode([
                    'infection_rate' => '40-60% in susceptible orchards',
                    'yield_impact' => '15-30% reduction in fruit quality',
                    'treatment_success_rate' => '80% with proper fungicide program',
                    'common_regions' => ['Pacific Northwest US', 'Great Lakes Region', 'Central Europe']
                ]),
                'source_url' => 'https://extension.wsu.edu/chelan-douglas/agriculture/treefruit/pestmanagement/diseasefactsheets/powderymildew/',
            ],
            [
                'name' => 'Cherry_(including_sour)___healthy',
                'description' => 'The cherry tree appears healthy with no visible signs of disease or pest damage.',
                'scientific_details' => 'Healthy cherry trees (Prunus spp.) exhibit robust growth, dark green leaves, and well-developed fruit. The plant is resistant to common pests and diseases. Leaves are smooth, glossy, and free of spots or abnormal coloration. Branches are strong and free of cankers or lesions. Fruit development is uniform, with proper sizing and coloration. The root system is extensive and fibrous, with numerous root hairs for efficient nutrient uptake.',
                'treatment_suggestions' => 'Maintain regular pruning, watering, and fertilization schedule. Monitor for early signs of common cherry diseases.',
                'prevention_methods' => 'Plant resistant varieties. Maintain proper tree spacing. Apply preventative fungicides. Monitor for pests. Prune annually. Ensure adequate water and fertilization.',
                'required_tools' => 'Pruning shears, watering can, fertilizer, soil testing kit, protective gear.',
                'environmental_factors' => 'Cherry trees thrive in full sun (6+ hours daily) and well-drained soil with pH 5.5-6.5. Require 500-1,000 chill hours. Optimal growing temperature range is 60-80°F (15-27°C).',
                'severity_level' => 'None',
                'average_treatment_time' => 0.0,
                'plant_type' => 'Cherry',
                'seasonal_prevalence' => json_encode(['Spring' => 'N/A', 'Summer' => 'N/A', 'Fall' => 'N/A', 'Winter' => 'N/A']),
                'statistics' => json_encode([
                    'productivity' => '10-20 pounds per mature tree',
                    'lifespan' => '30-40 years',
                    'pollination_requirements' => 'Most varieties require cross-pollination',
                    'common_varieties' => ['Bing', 'Rainier', 'Van', 'Montmorency']
                ]),
                'source_url' => null,
            ],
            [
                'name' => 'Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot',
                'description' => 'A fungal disease caused by Cercospora zeae-maydis that affects corn. It creates rectangular gray to tan lesions on corn leaves.',
                'scientific_details' => 'Cercospora leaf spot is caused by Cercospora zeae-maydis, a fungus that infects corn leaves. It produces small, circular to elongated, brick-red to brown pustules on the leaf surface. The fungus overwinters in infected plant material and can be spread by wind or splashing rain. Infection occurs on young leaves and develops rapidly in warm, humid conditions.',
                'treatment_suggestions' => 'Plant resistant hybrids. Rotate crops. Apply fungicides if economically feasible. Improve air circulation by proper plant spacing.',
                'prevention_methods' => 'Plant resistant hybrids. Rotate crops. Apply preventative fungicides. Monitor for pests. Prune annually. Ensure adequate water and fertilization.',
                'required_tools' => 'Pruning shears, fungicide sprayer, protective gear, sanitizing solution for tools, soil testing kit, fertilizer.',
                'environmental_factors' => 'Corn leaf spot is favored by warm temperatures (60-80°F/15-27°C) and high humidity. Leaf wetness duration is critical for infection. Plant spacing and air circulation are important for disease control.',
                'severity_level' => 'Moderate',
                'average_treatment_time' => 2.0,
                'plant_type' => 'Corn',
                'seasonal_prevalence' => json_encode(['Spring' => 'Moderate', 'Summer' => 'High', 'Fall' => 'Moderate', 'Winter' => 'None']),
                'statistics' => json_encode([
                    'infection_rate' => '30-60% in susceptible fields',
                    'yield_impact' => '10-30% reduction in marketable corn',
                    'treatment_success_rate' => '70-90% with proper fungicide program',
                    'common_regions' => ['Midwest US', 'Eastern US', 'Western Europe']
                ]),
                'source_url' => 'https://cropprotectionnetwork.org/resources/articles/diseases/gray-leaf-spot-of-corn',
            ],
            [
                'name' => 'Corn_(maize)___Common_rust_',
                'description' => 'A fungal disease caused by Puccinia sorghi that affects corn. It creates small, circular to elongated, brick-red to brown pustules on both leaf surfaces.',
                'scientific_details' => 'Common rust is caused by Puccinia sorghi, a fungus that infects corn leaves. It produces small, circular to elongated, brick-red to brown pustules on the leaf surface. The fungus overwinters in infected plant material and can be spread by wind or splashing rain. Infection occurs on young leaves and develops rapidly in warm, humid conditions.',
                'treatment_suggestions' => 'Plant resistant hybrids. Apply fungicides if disease pressure is high. Maintain proper field sanitation.',
                'prevention_methods' => 'Plant resistant hybrids. Apply preventative fungicides. Monitor for pests. Prune annually. Ensure adequate water and fertilization.',
                'required_tools' => 'Pruning shears, fungicide sprayer, protective gear, sanitizing solution for tools, soil testing kit, fertilizer.',
                'environmental_factors' => 'Common rust is favored by warm temperatures (60-80°F/15-27°C) and high humidity. Leaf wetness duration is critical for infection. Plant spacing and air circulation are important for disease control.',
                'severity_level' => 'Moderate',
                'average_treatment_time' => 2.0,
                'plant_type' => 'Corn',
                'seasonal_prevalence' => json_encode(['Spring' => 'Moderate', 'Summer' => 'High', 'Fall' => 'Moderate', 'Winter' => 'None']),
                'statistics' => json_encode([
                    'infection_rate' => '20-40% in susceptible fields',
                    'yield_impact' => '5-15% reduction in marketable corn',
                    'treatment_success_rate' => '80-95% with proper fungicide program',
                    'common_regions' => ['Midwest US', 'Eastern US', 'Western Europe']
                ]),
                'source_url' => 'https://cropprotectionnetwork.org/resources/articles/diseases/common-rust-of-corn',
            ],
            [
                'name' => 'Corn_(maize)___Northern_Leaf_Blight',
                'description' => 'A fungal disease caused by Exserohilum turcicum that affects corn. It creates long, elliptical, grayish-green to tan lesions on the leaves.',
                'scientific_details' => 'Northern leaf blight is caused by Exserohilum turcicum, a fungus that infects corn leaves. It produces long, elliptical, grayish-green to tan lesions on the leaf surface. The fungus overwinters in infected plant material and can be spread by wind or splashing rain. Infection occurs on young leaves and develops rapidly in warm, humid conditions.',
                'treatment_suggestions' => 'Plant resistant hybrids. Rotate crops. Apply fungicides when disease is first observed. Practice good field sanitation.',
                'prevention_methods' => 'Plant resistant hybrids. Rotate crops. Apply preventative fungicides. Monitor for pests. Prune annually. Ensure adequate water and fertilization.',
                'required_tools' => 'Pruning shears, fungicide sprayer, protective gear, sanitizing solution for tools, soil testing kit, fertilizer.',
                'environmental_factors' => 'Northern leaf blight is favored by warm temperatures (60-80°F/15-27°C) and high humidity. Leaf wetness duration is critical for infection. Plant spacing and air circulation are important for disease control.',
                'severity_level' => 'Moderate',
                'average_treatment_time' => 2.0,
                'plant_type' => 'Corn',
                'seasonal_prevalence' => json_encode(['Spring' => 'Moderate', 'Summer' => 'High', 'Fall' => 'Moderate', 'Winter' => 'None']),
                'statistics' => json_encode([
                    'infection_rate' => '10-30% in susceptible fields',
                    'yield_impact' => '5-15% reduction in marketable corn',
                    'treatment_success_rate' => '70-90% with proper fungicide program',
                    'common_regions' => ['Midwest US', 'Eastern US', 'Western Europe']
                ]),
                'source_url' => 'https://cropprotectionnetwork.org/resources/articles/diseases/northern-corn-leaf-blight',
            ],
            [
                'name' => 'Corn_(maize)___healthy',
                'description' => 'The corn plant appears healthy with no visible signs of disease or pest damage.',
                'scientific_details' => 'Healthy corn plants (Zea mays) display robust growth, dark green leaves, and well-developed fruit. The plant is resistant to common pests and diseases. Leaves are smooth, glossy, and free of spots or abnormal coloration. Branches are strong and free of cankers or lesions. Fruit development is uniform, with proper sizing and coloration. The root system is extensive and fibrous, with numerous root hairs for efficient nutrient uptake.',
                'treatment_suggestions' => 'Maintain proper fertilization and irrigation practices. Monitor for early signs of common corn diseases.',
                'prevention_methods' => 'Practice crop rotation (3-4 year cycle). Use mulch to prevent soil splash onto leaves. Provide adequate spacing between plants (18-36 inches). Water at soil level rather than overhead. Apply balanced fertilizer based on soil test results. Remove lower leaves that touch the soil. Monitor regularly for early signs of common diseases.',
                'required_tools' => 'Pruning shears, loppers, watering can, mulch, balanced fertilizer, soil testing kit.',
                'environmental_factors' => 'Corn plants prefer full sun (6-8 hours daily), well-drained soil with pH 6.0-6.8, consistent moisture (1-2 inches weekly), and temperatures between 65-85°F (18-29°C) for optimal growth and fruit production.',
                'severity_level' => 'None',
                'average_treatment_time' => 0.0,
                'plant_type' => 'Corn',
                'seasonal_prevalence' => json_encode(['Spring' => 'N/A', 'Summer' => 'N/A', 'Fall' => 'N/A', 'Winter' => 'N/A']),
                'statistics' => json_encode([
                    'productivity' => '100-200 pounds per plant for indeterminate varieties',
                    'growth_rate' => 'From seedling to first harvest in 60-100 days depending on variety',
                    'pollination' => 'Self-pollinating, enhanced by wind or mechanical vibration',
                    'common_varieties' => ['Roma', 'Beefsteak', 'Cherry', 'Heirloom', 'Determinate', 'Indeterminate']
                ]),
                'source_url' => null,
            ],
            [
                'name' => 'Grape___Black_rot',
                'description' => 'A fungal disease caused by Guignardia bidwellii that affects grapes. It causes black, sunken, circular lesions on leaves and rotting of the fruit.',
                'scientific_details' => 'Black rot is caused by the fungus Guignardia bidwellii, which infects grape leaves and fruit. It produces black, sunken, circular lesions on the leaf surface and rotting of the fruit. The fungus overwinters in cankers, mummified fruit, and dead wood. Spores are released during warm, wet periods and can infect throughout the growing season. The disease is particularly damaging in humid regions.',
                'treatment_suggestions' => 'Apply fungicides early in the growing season. Remove mummified fruit. Prune to improve air circulation. Remove infected leaves.',
                'prevention_methods' => 'Plant resistant varieties. Maintain proper tree spacing. Apply preventative fungicides. Monitor for pests. Prune annually. Ensure adequate water and fertilization.',
                'required_tools' => 'Pruning shears, fungicide sprayer, protective gear, sanitizing solution for tools, soil testing kit, fertilizer.',
                'environmental_factors' => 'Black rot is favored by warm temperatures (60-80°F/15-27°C) and high humidity. Wounds from hail, insects, or mechanical damage provide entry points for the pathogen. Plant spacing and air circulation are important for disease control.',
                'severity_level' => 'Moderate',
                'average_treatment_time' => 2.0,
                'plant_type' => 'Grape',
                'seasonal_prevalence' => json_encode(['Spring' => 'Moderate', 'Summer' => 'High', 'Fall' => 'Moderate', 'Winter' => 'None']),
                'statistics' => json_encode([
                    'infection_rate' => '20-40% in susceptible vineyards',
                    'yield_impact' => '10-30% reduction in grape quality',
                    'treatment_success_rate' => '80-90% with proper fungicide program',
                    'common_regions' => ['Northeast US', 'Midwest US', 'Northern Europe']
                ]),
                'source_url' => 'https://extension.umn.edu/plant-diseases/black-rot-grapes',
            ],
            [
                'name' => 'Grape___Esca_(Black_Measles)',
                'description' => 'A complex fungal disease that affects grapevines. It causes tiger-striped leaf patterns, black spotting on fruit, and eventual vine decline.',
                'scientific_details' => 'Esca (Black Measles) is caused by a complex of fungi including Botryosphaeria obtusa, Puccinia virens, and others. It produces tiger-striped leaf patterns, black spotting on fruit, and eventual vine decline. The disease is particularly damaging in humid regions.',
                'treatment_suggestions' => 'No effective chemical treatments exist. Remove and destroy infected vines. Use clean pruning tools. Avoid pruning during wet weather.',
                'prevention_methods' => 'Plant resistant varieties. Maintain proper tree spacing. Apply preventative fungicides. Monitor for pests. Prune annually. Ensure adequate water and fertilization.',
                'required_tools' => 'Pruning shears, fungicide sprayer, protective gear, sanitizing solution for tools, soil testing kit, fertilizer.',
                'environmental_factors' => 'Esca is favored by warm temperatures (60-80°F/15-27°C) and high humidity. Wounds from hail, insects, or mechanical damage provide entry points for the pathogen. Plant spacing and air circulation are important for disease control.',
                'severity_level' => 'Moderate',
                'average_treatment_time' => 2.0,
                'plant_type' => 'Grape',
                'seasonal_prevalence' => json_encode(['Spring' => 'Moderate', 'Summer' => 'High', 'Fall' => 'Moderate', 'Winter' => 'None']),
                'statistics' => json_encode([
                    'infection_rate' => '10-30% in susceptible vineyards',
                    'yield_impact' => '10-20% reduction in grape quality',
                    'treatment_success_rate' => '50-70% with combined approaches',
                    'common_regions' => ['Northeast US', 'Midwest US', 'Northern Europe']
                ]),
                'source_url' => 'https://grapes.extension.org/grapevine-measles-esca-black-measles/',
            ],
            [
                'name' => 'Grape___Leaf_blight_(Isariopsis_Leaf_Spot)',
                'description' => 'A fungal disease caused by Pseudocercospora vitis that affects grapevines. It creates brown lesions with dark borders on the leaves.',
                'scientific_details' => 'Leaf blight is caused by Pseudocercospora vitis, a fungus that infects grape leaves. It produces brown lesions with dark borders on the leaf surface. The fungus overwinters in infected plant material and can be spread by wind or splashing rain. Infection occurs on young leaves and develops rapidly in warm, humid conditions.',
                'treatment_suggestions' => 'Apply fungicides preventatively. Improve air circulation through proper pruning. Remove infected leaves. Maintain vineyard sanitation.',
                'prevention_methods' => 'Plant resistant varieties. Maintain proper tree spacing. Apply preventative fungicides. Monitor for pests. Prune annually. Ensure adequate water and fertilization.',
                'required_tools' => 'Pruning shears, fungicide sprayer, protective gear, sanitizing solution for tools, soil testing kit, fertilizer.',
                'environmental_factors' => 'Leaf blight is favored by warm temperatures (60-80°F/15-27°C) and high humidity. Leaf wetness duration is critical for infection. Plant spacing and air circulation are important for disease control.',
                'severity_level' => 'Moderate',
                'average_treatment_time' => 2.0,
                'plant_type' => 'Grape',
                'seasonal_prevalence' => json_encode(['Spring' => 'Moderate', 'Summer' => 'High', 'Fall' => 'Moderate', 'Winter' => 'None']),
                'statistics' => json_encode([
                    'infection_rate' => '10-20% in susceptible vineyards',
                    'yield_impact' => '10-20% reduction in grape quality',
                    'treatment_success_rate' => '70-80% with proper fungicide program',
                    'common_regions' => ['Northeast US', 'Midwest US', 'Northern Europe']
                ]),
                'source_url' => 'https://plantvillage.psu.edu/topics/grape/infos',
            ],
            [
                'name' => 'Grape___healthy',
                'description' => 'The grapevine appears healthy with no visible signs of disease or pest damage.',
                'scientific_details' => 'Healthy grapevines (Vitis spp.) exhibit robust growth, dark green leaves, and well-developed fruit. The plant is resistant to common pests and diseases. Leaves are smooth, glossy, and free of spots or abnormal coloration. Branches are strong and free of cankers or lesions. Fruit development is uniform, with proper sizing and coloration. The root system is extensive and fibrous, with numerous root hairs for efficient nutrient uptake.',
                'treatment_suggestions' => 'Continue regular pruning, training, and canopy management. Monitor for early signs of common grape diseases.',
                'prevention_methods' => 'Plant resistant varieties. Maintain proper tree spacing. Apply preventative fungicides. Monitor for pests. Prune annually. Ensure adequate water and fertilization.',
                'required_tools' => 'Pruning shears, fungicide sprayer, protective gear, sanitizing solution for tools, soil testing kit, fertilizer.',
                'environmental_factors' => 'Grapevines thrive in full sun (6+ hours daily) and well-drained soil with pH 5.5-6.5. Require 500-1,000 chill hours. Optimal growing temperature range is 60-80°F (15-27°C).',
                'severity_level' => 'None',
                'average_treatment_time' => 0.0,
                'plant_type' => 'Grape',
                'seasonal_prevalence' => json_encode(['Spring' => 'N/A', 'Summer' => 'N/A', 'Fall' => 'N/A', 'Winter' => 'N/A']),
                'statistics' => json_encode([
                    'productivity' => '10-20 pounds per mature vine',
                    'lifespan' => '30-40 years',
                    'pollination_requirements' => 'Most varieties require cross-pollination',
                    'common_varieties' => ['Cabernet Sauvignon', 'Chardonnay', 'Merlot', 'Pinot Noir']
                ]),
                'source_url' => null,
            ],
            [
                'name' => 'Orange___Haunglongbing_(Citrus_greening)',
                'description' => 'A bacterial disease caused by Candidatus Liberibacter that affects citrus trees. It causes mottled leaves, misshapen and bitter fruit, and eventual tree death.',
                'scientific_details' => 'Haunglongbing (Citrus greening) is caused by Candidatus Liberibacter, a bacterium that infects citrus trees. It causes mottled leaves, misshapen and bitter fruit, and eventual tree death. The bacterium is transmitted by psyllid vectors, primarily the Asian citrus psyllid (Diaphorina citri).',
                'treatment_suggestions' => 'No cure exists. Control psyllid vectors with insecticides. Remove and destroy infected trees. Plant disease-free nursery stock.',
                'prevention_methods' => 'Plant disease-free nursery stock. Control psyllid vectors with insecticides. Monitor for pests. Prune annually. Ensure adequate water and fertilization.',
                'required_tools' => 'Pruning shears, fungicide sprayer, insecticide, protective gear, sanitizing solution for tools, soil testing kit, fertilizer.',
                'environmental_factors' => 'Haunglongbing is favored by warm temperatures (70-90°F/21-32°C) and high humidity. Psyllid vectors are active in warm weather. Plant spacing and air circulation are important for disease control.',
                'severity_level' => 'Moderate',
                'average_treatment_time' => 2.0,
                'plant_type' => 'Citrus',
                'seasonal_prevalence' => json_encode(['Spring' => 'Moderate', 'Summer' => 'High', 'Fall' => 'Moderate', 'Winter' => 'None']),
                'statistics' => json_encode([
                    'infection_rate' => '10-30% in susceptible orchards',
                    'yield_impact' => '50-70% reduction in citrus production',
                    'treatment_success_rate' => '50-70% with proper integrated management',
                    'common_regions' => ['Florida US', 'California US', 'Mexico']
                ]),
                'source_url' => 'https://www.aphis.usda.gov/aphis/resources/pests-diseases/hungry-pests/the-threat/citrus-greening/citrus-greening-hp',
            ],
            [
                'name' => 'Peach___Bacterial_spot',
                'description' => 'A bacterial disease caused by Xanthomonas arboricola pv. pruni that affects peach trees. It causes small, dark lesions on leaves, fruit, and twigs.',
                'scientific_details' => 'Bacterial spot is caused by Xanthomonas arboricola pv. pruni, a bacterium that infects peach leaves, fruit, and twigs. It produces small, dark lesions on the plant surface. The bacterium is spread by splashing rain or irrigation water. Infection occurs on young leaves and develops rapidly in warm, humid conditions.',
                'treatment_suggestions' => 'Apply copper-based bactericides early in the season. Plant resistant varieties. Prune during dry weather. Avoid overhead irrigation.',
                'prevention_methods' => 'Plant resistant varieties. Maintain proper tree spacing. Apply preventative bactericides. Monitor for pests. Prune annually. Ensure adequate water and fertilization.',
                'required_tools' => 'Pruning shears, fungicide sprayer, bactericide, protective gear, sanitizing solution for tools, soil testing kit, fertilizer.',
                'environmental_factors' => 'Bacterial spot is favored by warm temperatures (60-80°F/15-27°C) and high humidity. Leaf wetness duration is critical for infection. Plant spacing and air circulation are important for disease control.',
                'severity_level' => 'Moderate',
                'average_treatment_time' => 2.0,
                'plant_type' => 'Peach',
                'seasonal_prevalence' => json_encode(['Spring' => 'Moderate', 'Summer' => 'High', 'Fall' => 'Moderate', 'Winter' => 'None']),
                'statistics' => json_encode([
                    'infection_rate' => '20-40% in susceptible orchards',
                    'yield_impact' => '10-20% reduction in peach production',
                    'treatment_success_rate' => '80-90% with proper bactericide program',
                    'common_regions' => ['Northeast US', 'Midwest US', 'Southern Europe']
                ]),
                'source_url' => 'https://extension.umn.edu/plant-diseases/bacterial-spot-stone-fruits',
            ],
            [
                'name' => 'Peach___healthy',
                'description' => 'The peach tree appears healthy with no visible signs of disease or pest damage.',
                'scientific_details' => 'Healthy peach trees (Prunus persica) exhibit robust growth, dark green leaves, and well-developed fruit. The plant is resistant to common pests and diseases. Leaves are smooth, glossy, and free of spots or abnormal coloration. Branches are strong and free of cankers or lesions. Fruit development is uniform, with proper sizing and coloration. The root system is extensive and fibrous, with numerous root hairs for efficient nutrient uptake.',
                'treatment_suggestions' => 'Maintain regular pruning, fertilization, and pest monitoring. Apply dormant sprays as preventative measures.',
                'prevention_methods' => 'Plant resistant varieties. Maintain proper tree spacing. Apply preventative fungicides. Monitor for pests. Prune annually. Ensure adequate water and fertilization.',
                'required_tools' => 'Pruning shears, fungicide sprayer, protective gear, sanitizing solution for tools, soil testing kit, fertilizer.',
                'environmental_factors' => 'Peach trees thrive in full sun (6+ hours daily) and well-drained soil with pH 5.5-6.5. Require 500-1,000 chill hours. Optimal growing temperature range is 60-80°F (15-27°C).',
                'severity_level' => 'None',
                'average_treatment_time' => 0.0,
                'plant_type' => 'Peach',
                'seasonal_prevalence' => json_encode(['Spring' => 'N/A', 'Summer' => 'N/A', 'Fall' => 'N/A', 'Winter' => 'N/A']),
                'statistics' => json_encode([
                    'productivity' => '10-20 pounds per mature tree',
                    'lifespan' => '30-40 years',
                    'pollination_requirements' => 'Most varieties require cross-pollination',
                    'common_varieties' => ['Bing', 'Rainier', 'Van', 'Montmorency']
                ]),
                'source_url' => null,
            ],
            [
                'name' => 'Pepper,_bell___Bacterial_spot',
                'description' => 'A bacterial disease caused by Xanthomonas species that affects pepper plants. It causes small, dark, water-soaked spots on leaves, stems, and fruit.',
                'scientific_details' => 'Bacterial spot is caused by Xanthomonas species, a bacterium that infects pepper leaves, stems, and fruit. It produces small, dark, water-soaked spots on the plant surface. The bacterium is spread by splashing rain or irrigation water. Infection occurs on young leaves and develops rapidly in warm, humid conditions.',
                'treatment_suggestions' => 'Use disease-free seeds and transplants. Rotate crops. Apply copper-based bactericides. Avoid overhead irrigation. Remove infected plants.',
                'prevention_methods' => 'Use disease-free seeds and transplants. Rotate crops. Apply preventative bactericides. Monitor for pests. Prune annually. Ensure adequate water and fertilization.',
                'required_tools' => 'Pruning shears, fungicide sprayer, bactericide, protective gear, sanitizing solution for tools, soil testing kit, fertilizer.',
                'environmental_factors' => 'Bacterial spot is favored by warm temperatures (60-80°F/15-27°C) and high humidity. Leaf wetness duration is critical for infection. Plant spacing and air circulation are important for disease control.',
                'severity_level' => 'Moderate',
                'average_treatment_time' => 2.0,
                'plant_type' => 'Pepper',
                'seasonal_prevalence' => json_encode(['Spring' => 'Moderate', 'Summer' => 'High', 'Fall' => 'Moderate', 'Winter' => 'None']),
                'statistics' => json_encode([
                    'infection_rate' => '10-20% in susceptible pepper plants',
                    'yield_impact' => '5-10% reduction in pepper production',
                    'treatment_success_rate' => '80-90% with proper bactericide program',
                    'common_regions' => ['Northeast US', 'Midwest US', 'Southern Europe']
                ]),
                'source_url' => 'https://extension.umn.edu/disease-management/bacterial-spot-peppers-and-tomatoes',
            ],
            [
                'name' => 'Pepper,_bell___healthy',
                'description' => 'The bell pepper plant appears healthy with no visible signs of disease or pest damage.',
                'scientific_details' => 'Healthy bell pepper plants (Capsicum annuum) exhibit robust growth, dark green leaves, and well-developed fruit. The plant is resistant to common pests and diseases. Leaves are smooth, glossy, and free of spots or abnormal coloration. Branches are strong and free of cankers or lesions. Fruit development is uniform, with proper sizing and coloration. The root system is extensive and fibrous, with numerous root hairs for efficient nutrient uptake.',
                'treatment_suggestions' => 'Maintain consistent watering and fertilization. Monitor for common pepper pests like aphids and pepper weevils.',
                'prevention_methods' => 'Plant resistant varieties. Maintain proper tree spacing. Apply preventative fungicides. Monitor for pests. Prune annually. Ensure adequate water and fertilization.',
                'required_tools' => 'Pruning shears, fungicide sprayer, protective gear, sanitizing solution for tools, soil testing kit, fertilizer.',
                'environmental_factors' => 'Bell pepper plants thrive in full sun (6+ hours daily) and well-drained soil with pH 6.0-6.8. Require 500-1,000 chill hours. Optimal growing temperature range is 65-85°F (18-29°C).',
                'severity_level' => 'None',
                'average_treatment_time' => 0.0,
                'plant_type' => 'Pepper',
                'seasonal_prevalence' => json_encode(['Spring' => 'N/A', 'Summer' => 'N/A', 'Fall' => 'N/A', 'Winter' => 'N/A']),
                'statistics' => json_encode([
                    'productivity' => '10-20 pounds per plant for indeterminate varieties',
                    'growth_rate' => 'From seedling to first harvest in 60-100 days depending on variety',
                    'pollination' => 'Self-pollinating, enhanced by wind or mechanical vibration',
                    'common_varieties' => ['Roma', 'Beefsteak', 'Cherry', 'Heirloom', 'Determinate', 'Indeterminate']
                ]),
                'source_url' => null,
            ],
            [
                'name' => 'Potato___Early_blight',
                'description' => 'A fungal disease caused by Alternaria solani that affects potato plants. It causes dark, concentric rings forming a target-like pattern on lower leaves.',
                'scientific_details' => 'Early blight is caused by Alternaria solani, a fungus that infects potato leaves. It produces dark, concentric rings on the leaf surface. The fungus overwinters in infected plant material and can be spread by wind or splashing rain. Infection occurs on young leaves and develops rapidly in warm, humid conditions.',
                'treatment_suggestions' => 'Apply fungicides preventatively. Practice crop rotation. Remove infected leaves. Improve air circulation. Avoid overhead irrigation.',
                'prevention_methods' => 'Plant resistant varieties. Practice crop rotation (3-4 year cycle). Apply preventative fungicides. Monitor for pests. Prune annually. Ensure adequate water and fertilization.',
                'required_tools' => 'Pruning shears, fungicide sprayer, protective gear, sanitizing solution for tools, soil testing kit, fertilizer.',
                'environmental_factors' => 'Early blight is favored by warm temperatures (60-80°F/15-27°C) and high humidity. Leaf wetness duration is critical for infection. Plant spacing and air circulation are important for disease control.',
                'severity_level' => 'Moderate',
                'average_treatment_time' => 2.0,
                'plant_type' => 'Potato',
                'seasonal_prevalence' => json_encode(['Spring' => 'Moderate', 'Summer' => 'High', 'Fall' => 'Moderate', 'Winter' => 'None']),
                'statistics' => json_encode([
                    'infection_rate' => '20-40% in susceptible potato fields',
                    'yield_impact' => '10-20% reduction in potato production',
                    'treatment_success_rate' => '70-90% with proper fungicide program',
                    'common_regions' => ['Northeast US', 'Midwest US', 'Western Europe']
                ]),
                'source_url' => 'https://extension.umn.edu/diseases/early-blight-tomato-and-potato',
            ],
            [
                'name' => 'Potato___Late_blight',
                'description' => 'A devastating water mold disease caused by Phytophthora infestans that affects potato plants. It causes dark, water-soaked lesions on leaves and stems, and can rot tubers.',
                'scientific_details' => 'Late blight is caused by Phytophthora infestans, a water mold that infects potato leaves, stems, and tubers. It produces dark, water-soaked lesions on the plant surface. The fungus overwinters in infected plant material and can be spread by splashing rain or irrigation water. Infection occurs on young leaves and develops rapidly in warm, humid conditions.',
                'treatment_suggestions' => 'Apply fungicides preventatively. Plant resistant varieties. Destroy volunteer potatoes. Harvest during dry weather. Store tubers properly.',
                'prevention_methods' => 'Plant resistant varieties. Destroy volunteer potatoes. Harvest during dry weather. Store tubers properly. Apply preventative fungicides. Monitor for pests. Prune annually. Ensure adequate water and fertilization.',
                'required_tools' => 'Pruning shears, fungicide sprayer, protective gear, sanitizing solution for tools, soil testing kit, fertilizer.',
                'environmental_factors' => 'Late blight is favored by warm temperatures (60-80°F/15-27°C) and high humidity. Leaf wetness duration is critical for infection. Plant spacing and air circulation are important for disease control.',
                'severity_level' => 'Moderate',
                'average_treatment_time' => 2.0,
                'plant_type' => 'Potato',
                'seasonal_prevalence' => json_encode(['Spring' => 'Moderate', 'Summer' => 'High', 'Fall' => 'Moderate', 'Winter' => 'None']),
                'statistics' => json_encode([
                    'infection_rate' => '10-20% in susceptible potato fields',
                    'yield_impact' => '5-10% reduction in potato production',
                    'treatment_success_rate' => '70-90% with proper fungicide program',
                    'common_regions' => ['Northeast US', 'Midwest US', 'Western Europe']
                ]),
                'source_url' => 'https://extension.umn.edu/diseases/late-blight',
            ],
            [
                'name' => 'Potato___healthy',
                'description' => 'The potato plant appears healthy with no visible signs of disease or pest damage.',
                'scientific_details' => 'Healthy potato plants (Solanum tuberosum) exhibit robust growth, dark green leaves, and well-developed fruit. The plant is resistant to common pests and diseases. Leaves are smooth, glossy, and free of spots or abnormal coloration. Branches are strong and free of cankers or lesions. Fruit development is uniform, with proper sizing and coloration. The root system is extensive and fibrous, with numerous root hairs for efficient nutrient uptake.',
                'treatment_suggestions' => 'Maintain consistent soil moisture. Hill plants as they grow. Monitor for common potato pests like Colorado potato beetle.',
                'prevention_methods' => 'Plant resistant varieties. Hill plants as they grow. Monitor for common potato pests. Prune annually. Ensure adequate water and fertilization.',
                'required_tools' => 'Pruning shears, watering can, soil testing kit, fertilizer.',
                'environmental_factors' => 'Potato plants prefer full sun (6+ hours daily) and well-drained soil with pH 5.5-6.5. Require 500-1,000 chill hours. Optimal growing temperature range is 60-80°F (15-27°C).',
                'severity_level' => 'None',
                'average_treatment_time' => 0.0,
                'plant_type' => 'Potato',
                'seasonal_prevalence' => json_encode(['Spring' => 'N/A', 'Summer' => 'N/A', 'Fall' => 'N/A', 'Winter' => 'N/A']),
                'statistics' => json_encode([
                    'productivity' => '100-200 pounds per plant for indeterminate varieties',
                    'growth_rate' => 'From seedling to first harvest in 60-100 days depending on variety',
                    'pollination' => 'Self-pollinating, enhanced by wind or mechanical vibration',
                    'common_varieties' => ['Roma', 'Beefsteak', 'Cherry', 'Heirloom', 'Determinate', 'Indeterminate']
                ]),
                'source_url' => null,
            ],
            [
                'name' => 'Raspberry___healthy',
                'description' => 'The raspberry plant appears healthy with no visible signs of disease or pest damage.',
                'scientific_details' => 'Healthy raspberry plants (Rubus spp.) exhibit robust growth, dark green leaves, and well-developed fruit. The plant is resistant to common pests and diseases. Leaves are smooth, glossy, and free of spots or abnormal coloration. Branches are strong and free of cankers or lesions. Fruit development is uniform, with proper sizing and coloration. The root system is extensive and fibrous, with numerous root hairs for efficient nutrient uptake.',
                'treatment_suggestions' => 'Prune out old canes after fruiting. Maintain good air circulation. Provide support for canes. Monitor for common raspberry pests.',
                'prevention_methods' => 'Plant resistant varieties. Maintain proper tree spacing. Apply preventative fungicides. Monitor for pests. Prune annually. Ensure adequate water and fertilization.',
                'required_tools' => 'Pruning shears, fungicide sprayer, protective gear, sanitizing solution for tools, soil testing kit, fertilizer.',
                'environmental_factors' => 'Raspberry plants thrive in full sun (6+ hours daily) and well-drained soil with pH 5.5-6.5. Require 500-1,000 chill hours. Optimal growing temperature range is 60-80°F (15-27°C).',
                'severity_level' => 'None',
                'average_treatment_time' => 0.0,
                'plant_type' => 'Raspberry',
                'seasonal_prevalence' => json_encode(['Spring' => 'N/A', 'Summer' => 'N/A', 'Fall' => 'N/A', 'Winter' => 'N/A']),
                'statistics' => json_encode([
                    'productivity' => '10-20 pounds per plant for indeterminate varieties',
                    'growth_rate' => 'From seedling to first harvest in 60-100 days depending on variety',
                    'pollination' => 'Self-pollinating, enhanced by wind or mechanical vibration',
                    'common_varieties' => ['Raspberry', 'Blackberry', 'Strawberry']
                ]),
                'source_url' => null,
            ],
            [
                'name' => 'Soybean___healthy',
                'description' => 'The soybean plant appears healthy with no visible signs of disease or pest damage.',
                'scientific_details' => 'Healthy soybean plants (Glycine max) exhibit robust growth, dark green leaves, and well-developed fruit. The plant is resistant to common pests and diseases. Leaves are smooth, glossy, and free of spots or abnormal coloration. Branches are strong and free of cankers or lesions. Fruit development is uniform, with proper sizing and coloration. The root system is extensive and fibrous, with numerous root hairs for efficient nutrient uptake.',
                'treatment_suggestions' => 'Rotate crops. Plant at appropriate time. Use high-quality seeds. Monitor for common soybean pests and diseases.',
                'prevention_methods' => 'Plant resistant varieties. Rotate crops. Plant at appropriate time. Use high-quality seeds. Monitor for common soybean pests and diseases. Prune annually. Ensure adequate water and fertilization.',
                'required_tools' => 'Pruning shears, fungicide sprayer, protective gear, sanitizing solution for tools, soil testing kit, fertilizer.',
                'environmental_factors' => 'Soybean plants thrive in full sun (6+ hours daily) and well-drained soil with pH 5.5-6.5. Require 500-1,000 chill hours. Optimal growing temperature range is 60-80°F (15-27°C).',
                'severity_level' => 'None',
                'average_treatment_time' => 0.0,
                'plant_type' => 'Soybean',
                'seasonal_prevalence' => json_encode(['Spring' => 'N/A', 'Summer' => 'N/A', 'Fall' => 'N/A', 'Winter' => 'N/A']),
                'statistics' => json_encode([
                    'productivity' => '100-200 pounds per acre',
                    'growth_rate' => 'From seedling to first harvest in 60-100 days depending on variety',
                    'pollination' => 'Self-pollinating, enhanced by wind or mechanical vibration',
                    'common_varieties' => ['Roundup Ready', 'LibertyLink', 'Bt']
                ]),
                'source_url' => null,
            ],
            [
                'name' => 'Squash___Powdery_mildew',
                'description' => 'A fungal disease caused by several fungi that affects squash plants. It appears as white powdery spots on the leaves and stems.',
                'scientific_details' => 'Powdery mildew on squash is caused by several fungi, primarily Sphaerotheca fuliginea and Erysiphe cichoracearum. It produces white, powdery spots on the leaf and stem surface. The fungus overwinters in infected plant material and can be spread by wind or splashing rain. Infection occurs on young leaves and develops rapidly in warm, humid conditions.',
                'treatment_suggestions' => 'Apply fungicides at first sign of disease. Plant resistant varieties. Improve air circulation. Avoid overhead irrigation.',
                'prevention_methods' => 'Plant resistant varieties. Apply preventative fungicides. Monitor for pests. Prune annually. Ensure adequate water and fertilization.',
                'required_tools' => 'Pruning shears, fungicide sprayer, protective gear, sanitizing solution for tools, soil testing kit, fertilizer.',
                'environmental_factors' => 'Powdery mildew is favored by warm temperatures (60-80°F/15-27°C) and high humidity. Leaf wetness duration is critical for infection. Plant spacing and air circulation are important for disease control.',
                'severity_level' => 'Moderate',
                'average_treatment_time' => 2.0,
                'plant_type' => 'Squash',
                'seasonal_prevalence' => json_encode(['Spring' => 'Moderate', 'Summer' => 'High', 'Fall' => 'Moderate', 'Winter' => 'None']),
                'statistics' => json_encode([
                    'infection_rate' => '20-40% in susceptible squash plants',
                    'yield_impact' => '10-20% reduction in squash production',
                    'treatment_success_rate' => '70-90% with proper fungicide program',
                    'common_regions' => ['Northeast US', 'Midwest US', 'Western Europe']
                ]),
                'source_url' => 'https://extension.umn.edu/diseases/powdery-mildew-cucurbits',
            ],
            [
                'name' => 'Strawberry___Leaf_scorch',
                'description' => 'A fungal disease caused by Diplocarpon earlianum that affects strawberry plants. It causes purple to red spots on leaves that eventually turn brown with a scorched appearance.',
                'scientific_details' => 'Leaf scorch is caused by Diplocarpon earlianum, a fungus that infects strawberry leaves. It produces purple to red spots on the leaf surface. The fungus overwinters in infected plant material and can be spread by wind or splashing rain. Infection occurs on young leaves and develops rapidly in warm, humid conditions.',
                'treatment_suggestions' => 'Remove infected leaves. Apply fungicides. Avoid overhead irrigation. Ensure good air circulation. Renovate beds after harvest.',
                'prevention_methods' => 'Plant resistant varieties. Apply preventative fungicides. Monitor for pests. Prune annually. Ensure adequate water and fertilization.',
                'required_tools' => 'Pruning shears, fungicide sprayer, protective gear, sanitizing solution for tools, soil testing kit, fertilizer.',
                'environmental_factors' => 'Leaf scorch is favored by warm temperatures (60-80°F/15-27°C) and high humidity. Leaf wetness duration is critical for infection. Plant spacing and air circulation are important for disease control.',
                'severity_level' => 'Moderate',
                'average_treatment_time' => 2.0,
                'plant_type' => 'Strawberry',
                'seasonal_prevalence' => json_encode(['Spring' => 'Moderate', 'Summer' => 'High', 'Fall' => 'Moderate', 'Winter' => 'None']),
                'statistics' => json_encode([
                    'infection_rate' => '10-20% in susceptible strawberry plants',
                    'yield_impact' => '5-10% reduction in strawberry production',
                    'treatment_success_rate' => '70-90% with proper fungicide program',
                    'common_regions' => ['Northeast US', 'Midwest US', 'Western Europe']
                ]),
                'source_url' => 'https://extension.umn.edu/fruit/growing-strawberries-home-garden#common-diseases-506656',
            ],
            [
                'name' => 'Strawberry___healthy',
                'description' => 'The strawberry plant appears healthy with no visible signs of disease or pest damage.',
                'scientific_details' => 'Healthy strawberry plants (Fragaria spp.) exhibit robust growth, dark green leaves, and well-developed fruit. The plant is resistant to common pests and diseases. Leaves are smooth, glossy, and free of spots or abnormal coloration. Branches are strong and free of cankers or lesions. Fruit development is uniform, with proper sizing and coloration. The root system is extensive and fibrous, with numerous root hairs for efficient nutrient uptake.',
                'treatment_suggestions' => 'Mulch around plants. Provide adequate water. Renovate beds after harvest. Monitor for common strawberry pests.',
                'prevention_methods' => 'Plant resistant varieties. Mulch around plants. Provide adequate water. Renovate beds after harvest. Monitor for common strawberry pests. Prune annually. Ensure adequate water and fertilization.',
                'required_tools' => 'Pruning shears, watering can, mulch, soil testing kit, fertilizer.',
                'environmental_factors' => 'Strawberry plants thrive in full sun (6+ hours daily) and well-drained soil with pH 5.5-6.5. Require 500-1,000 chill hours. Optimal growing temperature range is 60-80°F (15-27°C).',
                'severity_level' => 'None',
                'average_treatment_time' => 0.0,
                'plant_type' => 'Strawberry',
                'seasonal_prevalence' => json_encode(['Spring' => 'N/A', 'Summer' => 'N/A', 'Fall' => 'N/A', 'Winter' => 'N/A']),
                'statistics' => json_encode([
                    'productivity' => '10-20 pounds per plant for indeterminate varieties',
                    'growth_rate' => 'From seedling to first harvest in 60-100 days depending on variety',
                    'pollination' => 'Self-pollinating, enhanced by wind or mechanical vibration',
                    'common_varieties' => ['Raspberry', 'Blackberry', 'Strawberry']
                ]),
                'source_url' => null,
            ],
            [
                'name' => 'Tomato___Bacterial_spot',
                'description' => 'A bacterial disease caused by Xanthomonas species that affects tomato plants. It causes small, dark, water-soaked spots on leaves, stems, and fruit.',
                'scientific_details' => 'Bacterial spot is caused by Xanthomonas species, a bacterium that infects tomato leaves, stems, and fruit. It produces small, dark, water-soaked spots on the plant surface. The bacterium is spread by splashing rain or irrigation water. Infection occurs on young leaves and develops rapidly in warm, humid conditions.',
                'treatment_suggestions' => 'Use disease-free seeds and transplants. Rotate crops. Apply copper-based bactericides. Avoid overhead irrigation. Remove infected plants.',
                'prevention_methods' => 'Use disease-free seeds and transplants. Rotate crops. Apply preventative bactericides. Monitor for pests. Prune annually. Ensure adequate water and fertilization.',
                'required_tools' => 'Pruning shears, fungicide sprayer, bactericide, protective gear, sanitizing solution for tools, soil testing kit, fertilizer.',
                'environmental_factors' => 'Bacterial spot is favored by warm temperatures (60-80°F/15-27°C) and high humidity. Leaf wetness duration is critical for infection. Plant spacing and air circulation are important for disease control.',
                'severity_level' => 'Moderate',
                'average_treatment_time' => 2.0,
                'plant_type' => 'Tomato',
                'seasonal_prevalence' => json_encode(['Spring' => 'Moderate', 'Summer' => 'High', 'Fall' => 'Moderate', 'Winter' => 'None']),
                'statistics' => json_encode([
                    'infection_rate' => '10-20% in susceptible tomato plants',
                    'yield_impact' => '5-10% reduction in tomato production',
                    'treatment_success_rate' => '80-90% with proper bactericide program',
                    'common_regions' => ['Northeast US', 'Midwest US', 'Western Europe']
                ]),
                'source_url' => 'https://extension.umn.edu/disease-management/bacterial-spot-peppers-and-tomatoes',
            ],
            [
                'name' => 'Tomato___Early_blight',
                'description' => 'A fungal disease caused by Alternaria solani that affects tomato plants. It causes dark, concentric rings forming a target-like pattern on lower leaves.',
                'scientific_details' => 'Early blight is caused by Alternaria solani, a fungus that infects tomato leaves. It produces dark, concentric rings on the leaf surface. The fungus overwinters in infected plant material and can be spread by wind or splashing rain. Infection occurs on young leaves and develops rapidly in warm, humid conditions.',
                'treatment_suggestions' => 'Apply fungicides preventatively. Practice crop rotation. Remove infected leaves. Improve air circulation. Stake plants.',
                'prevention_methods' => 'Plant resistant varieties. Practice crop rotation (3-4 year cycle). Apply preventative fungicides. Monitor for pests. Prune annually. Ensure adequate water and fertilization.',
                'required_tools' => 'Pruning shears, fungicide sprayer, protective gear, sanitizing solution for tools, soil testing kit, fertilizer.',
                'environmental_factors' => 'Early blight is favored by warm temperatures (60-80°F/15-27°C) and high humidity. Leaf wetness duration is critical for infection. Plant spacing and air circulation are important for disease control.',
                'severity_level' => 'Moderate',
                'average_treatment_time' => 2.0,
                'plant_type' => 'Tomato',
                'seasonal_prevalence' => json_encode(['Spring' => 'Moderate', 'Summer' => 'High', 'Fall' => 'Moderate', 'Winter' => 'None']),
                'statistics' => json_encode([
                    'infection_rate' => '10-20% in susceptible tomato plants',
                    'yield_impact' => '5-10% reduction in tomato production',
                    'treatment_success_rate' => '70-90% with proper fungicide program',
                    'common_regions' => ['Northeast US', 'Midwest US', 'Western Europe']
                ]),
                'source_url' => 'https://extension.umn.edu/diseases/early-blight-tomato-and-potato',
            ],
            [
                'name' => 'Tomato___Late_blight',
                'description' => 'A water mold disease caused by Phytophthora infestans that affects tomato plants. It causes dark, water-soaked lesions on leaves, stems, and fruit.',
                'scientific_details' => 'Late blight is caused by Phytophthora infestans, a water mold that infects tomato leaves, stems, and fruit. It produces dark, water-soaked lesions on the plant surface. The fungus overwinters in infected plant material and can be spread by splashing rain or irrigation water. Infection occurs on young leaves and develops rapidly in warm, humid conditions.',
                'treatment_suggestions' => 'Apply fungicides preventatively. Plant resistant varieties. Remove infected plants. Improve air circulation. Avoid overhead irrigation.',
                'prevention_methods' => 'Plant resistant varieties. Remove infected plants. Improve air circulation. Avoid overhead irrigation. Apply preventative fungicides. Monitor for pests. Prune annually. Ensure adequate water and fertilization.',
                'required_tools' => 'Pruning shears, fungicide sprayer, protective gear, sanitizing solution for tools, soil testing kit, fertilizer.',
                'environmental_factors' => 'Late blight is favored by warm temperatures (60-80°F/15-27°C) and high humidity. Leaf wetness duration is critical for infection. Plant spacing and air circulation are important for disease control.',
                'severity_level' => 'Moderate',
                'average_treatment_time' => 2.0,
                'plant_type' => 'Tomato',
                'seasonal_prevalence' => json_encode(['Spring' => 'Moderate', 'Summer' => 'High', 'Fall' => 'Moderate', 'Winter' => 'None']),
                'statistics' => json_encode([
                    'infection_rate' => '10-20% in susceptible tomato plants',
                    'yield_impact' => '5-10% reduction in tomato production',
                    'treatment_success_rate' => '70-90% with proper fungicide program',
                    'common_regions' => ['Northeast US', 'Midwest US', 'Western Europe']
                ]),
                'source_url' => 'https://extension.umn.edu/diseases/late-blight',
            ],
            [
                'name' => 'Tomato___Leaf_Mold',
                'description' => 'A fungal disease caused by Passalora fulva that affects tomato plants. It causes pale green to yellow spots on the upper leaf surface and olive-green to grayish-brown fuzzy growth on the lower leaf surface.',
                'scientific_details' => 'Leaf mold is caused by Passalora fulva, a fungus that infects tomato leaves. It produces pale green to yellow spots on the upper leaf surface and olive-green to grayish-brown fuzzy growth on the lower leaf surface. The fungus overwinters in infected plant material and can be spread by wind or splashing rain. Infection occurs on young leaves and develops rapidly in warm, humid conditions.',
                'treatment_suggestions' => 'Improve air circulation. Reduce humidity in greenhouses. Apply fungicides. Remove infected leaves. Avoid overhead irrigation.',
                'prevention_methods' => 'Plant resistant varieties. Improve air circulation. Reduce humidity in greenhouses. Apply preventative fungicides. Monitor for pests. Prune annually. Ensure adequate water and fertilization.',
                'required_tools' => 'Pruning shears, fungicide sprayer, protective gear, sanitizing solution for tools, soil testing kit, fertilizer.',
                'environmental_factors' => 'Leaf mold is favored by warm temperatures (60-80°F/15-27°C) and high humidity. Leaf wetness duration is critical for infection. Plant spacing and air circulation are important for disease control.',
                'severity_level' => 'Moderate',
                'average_treatment_time' => 2.0,
                'plant_type' => 'Tomato',
                'seasonal_prevalence' => json_encode(['Spring' => 'Moderate', 'Summer' => 'High', 'Fall' => 'Moderate', 'Winter' => 'None']),
                'statistics' => json_encode([
                    'infection_rate' => '10-20% in susceptible tomato plants',
                    'yield_impact' => '5-10% reduction in tomato production',
                    'treatment_success_rate' => '70-90% with proper fungicide program',
                    'common_regions' => ['Northeast US', 'Midwest US', 'Western Europe']
                ]),
                'source_url' => 'https://extension.umn.edu/diseases/leaf-mold-tomato',
            ],
            [
                'name' => 'Tomato___Septoria_leaf_spot',
                'description' => 'A fungal disease caused by Septoria lycopersici that affects tomato plants. It causes small, circular spots with dark borders and light centers on leaves.',
                'scientific_details' => 'Septoria leaf spot is caused by Septoria lycopersici, a fungus that infects tomato leaves. It produces small, circular spots with dark borders and light centers on the leaf surface. The fungus overwinters in infected plant material and can be spread by wind or splashing rain. Infection occurs on young leaves and develops rapidly in warm, humid conditions.',
                'treatment_suggestions' => 'Apply fungicides preventatively. Remove infected leaves. Practice crop rotation. Mulch around plants. Avoid overhead irrigation.',
                'prevention_methods' => 'Plant resistant varieties. Remove infected leaves. Practice crop rotation. Mulch around plants. Avoid overhead irrigation. Apply preventative fungicides. Monitor for pests. Prune annually. Ensure adequate water and fertilization.',
                'required_tools' => 'Pruning shears, fungicide sprayer, protective gear, sanitizing solution for tools, soil testing kit, fertilizer.',
                'environmental_factors' => 'Septoria leaf spot is favored by warm temperatures (60-80°F/15-27°C) and high humidity. Leaf wetness duration is critical for infection. Plant spacing and air circulation are important for disease control.',
                'severity_level' => 'Moderate',
                'average_treatment_time' => 2.0,
                'plant_type' => 'Tomato',
                'seasonal_prevalence' => json_encode(['Spring' => 'Moderate', 'Summer' => 'High', 'Fall' => 'Moderate', 'Winter' => 'None']),
                'statistics' => json_encode([
                    'infection_rate' => '10-20% in susceptible tomato plants',
                    'yield_impact' => '5-10% reduction in tomato production',
                    'treatment_success_rate' => '70-90% with proper fungicide program',
                    'common_regions' => ['Northeast US', 'Midwest US', 'Western Europe']
                ]),
                'source_url' => 'https://extension.umn.edu/diseases/septoria-leaf-spot-tomato',
            ],
            [
                'name' => 'Tomato___Spider_mites Two-spotted_spider_mite',
                'description' => 'A pest infestation by tiny arachnids that causes stippling on leaves, webbing, and eventual leaf yellowing and death.',
                'scientific_details' => 'Spider mites are caused by Tetranychus urticae, a mite that infects tomato leaves. It produces stippling on the leaf surface and webbing. The mite overwinters in soil and can be spread by splashing rain or irrigation water. Infection occurs on young leaves and develops rapidly in warm, humid conditions.',
                'treatment_suggestions' => 'Increase humidity. Apply insecticidal soap or horticultural oil. Introduce predatory mites. Remove heavily infested plants.',
                'prevention_methods' => 'Plant resistant varieties. Increase humidity. Apply insecticidal soap or horticultural oil. Introduce predatory mites. Remove heavily infested plants. Monitor for pests. Prune annually. Ensure adequate water and fertilization.',
                'required_tools' => 'Pruning shears, fungicide sprayer, insecticide, protective gear, sanitizing solution for tools, soil testing kit, fertilizer.',
                'environmental_factors' => 'Spider mites thrive in warm temperatures (60-80°F/15-27°C) and high humidity. Leaf wetness duration is critical for infection. Plant spacing and air circulation are important for disease control.',
                'severity_level' => 'Moderate',
                'average_treatment_time' => 2.0,
                'plant_type' => 'Tomato',
                'seasonal_prevalence' => json_encode(['Spring' => 'Moderate', 'Summer' => 'High', 'Fall' => 'Moderate', 'Winter' => 'None']),
                'statistics' => json_encode([
                    'infection_rate' => '10-20% in susceptible tomato plants',
                    'yield_impact' => '5-10% reduction in tomato production',
                    'treatment_success_rate' => '70-90% with proper fungicide program',
                    'common_regions' => ['Northeast US', 'Midwest US', 'Western Europe']
                ]),
                'source_url' => 'https://extension.umn.edu/yard-and-garden-insects/spider-mites',
            ],
            [
                'name' => 'Tomato___Target_Spot',
                'description' => 'A fungal disease caused by Corynespora cassiicola that affects tomato plants. It causes circular brown spots with concentric rings that resemble a target.',
                'scientific_details' => 'Target spot is caused by Corynespora cassiicola, a fungus that infects tomato leaves. It produces circular brown spots with concentric rings on the leaf surface. The fungus overwinters in infected plant material and can be spread by wind or splashing rain. Infection occurs on young leaves and develops rapidly in warm, humid conditions.',
                'treatment_suggestions' => 'Apply fungicides. Remove infected leaves. Improve air circulation. Avoid overhead irrigation. Practice crop rotation.',
                'prevention_methods' => 'Plant resistant varieties. Apply preventative fungicides. Monitor for pests. Prune annually. Ensure adequate water and fertilization. Practice crop rotation.',
                'required_tools' => 'Pruning shears, fungicide sprayer, protective gear, sanitizing solution for tools, soil testing kit, fertilizer.',
                'environmental_factors' => 'Target spot is favored by warm temperatures (60-80°F/15-27°C) and high humidity. Leaf wetness duration is critical for infection. Plant spacing and air circulation are important for disease control.',
                'severity_level' => 'Moderate',
                'average_treatment_time' => 2.0,
                'plant_type' => 'Tomato',
                'seasonal_prevalence' => json_encode(['Spring' => 'Moderate', 'Summer' => 'High', 'Fall' => 'Moderate', 'Winter' => 'None']),
                'statistics' => json_encode([
                    'infection_rate' => '10-20% in susceptible tomato plants',
                    'yield_impact' => '5-10% reduction in tomato production',
                    'treatment_success_rate' => '70-90% with proper fungicide program',
                    'common_regions' => ['Northeast US', 'Midwest US', 'Western Europe']
                ]),
                'source_url' => 'https://edis.ifas.ufl.edu/publication/PP121',
            ],
            [
                'name' => 'Tomato___Tomato_Yellow_Leaf_Curl_Virus',
                'description' => 'A viral disease transmitted by whiteflies that affects tomato plants. It causes yellowing and upward curling of leaves, stunted growth, and reduced fruit production.',
                'scientific_details' => 'Tomato yellow leaf curl virus is caused by Tomato yellow leaf curl virus (TYLCV), a virus transmitted by whiteflies (Bemisia tabaci). It causes yellowing and upward curling of leaves, stunted growth, and reduced fruit production. The virus is transmitted by mechanical inoculation and by whitefly vectors.',
                'treatment_suggestions' => 'Control whitefly vectors with insecticides or insecticidal soap. Use reflective mulches. Plant resistant varieties. Remove infected plants.',
                'prevention_methods' => 'Plant resistant varieties. Control whitefly vectors with insecticides. Use reflective mulches. Monitor for pests. Prune annually. Ensure adequate water and fertilization.',
                'required_tools' => 'Pruning shears, fungicide sprayer, insecticide, protective gear, sanitizing solution for tools, soil testing kit, fertilizer.',
                'environmental_factors' => 'Tomato yellow leaf curl virus is favored by warm temperatures (60-80°F/15-27°C) and high humidity. Whitefly vectors are active in warm weather. Plant spacing and air circulation are important for disease control.',
                'severity_level' => 'Moderate',
                'average_treatment_time' => 2.0,
                'plant_type' => 'Tomato',
                'seasonal_prevalence' => json_encode(['Spring' => 'Moderate', 'Summer' => 'High', 'Fall' => 'Moderate', 'Winter' => 'None']),
                'statistics' => json_encode([
                    'infection_rate' => '10-20% in susceptible tomato plants',
                    'yield_impact' => '5-10% reduction in tomato production',
                    'treatment_success_rate' => '70-90% with proper integrated management',
                    'common_regions' => ['Northeast US', 'Midwest US', 'Western Europe']
                ]),
                'source_url' => 'https://extension.umn.edu/diseases/tomato-yellow-leaf-curl-virus',
            ],
            [
                'name' => 'Tomato___Tomato_mosaic_virus',
                'description' => 'A viral disease that affects tomato plants. It causes mottled light and dark green on leaves, stunted growth, and sometimes fruit deformation.',
                'scientific_details' => 'Tomato mosaic virus is caused by Tomato mosaic virus (ToMV), a virus that infects tomato plants. It causes mottled light and dark green on leaves, stunted growth, and sometimes fruit deformation. The virus is transmitted by mechanical inoculation and by whitefly vectors.',
                'treatment_suggestions' => 'No cure exists. Remove and destroy infected plants. Control aphid vectors. Disinfect tools. Plant resistant varieties. Wash hands after handling tobacco products.',
                'prevention_methods' => 'Plant resistant varieties. Control aphid vectors. Disinfect tools. Wash hands after handling tobacco products. Monitor for pests. Prune annually. Ensure adequate water and fertilization.',
                'required_tools' => 'Pruning shears, fungicide sprayer, insecticide, protective gear, sanitizing solution for tools, soil testing kit, fertilizer.',
                'environmental_factors' => 'Tomato mosaic virus is favored by warm temperatures (60-80°F/15-27°C) and high humidity. Whitefly vectors are active in warm weather. Plant spacing and air circulation are important for disease control.',
                'severity_level' => 'Moderate',
                'average_treatment_time' => 2.0,
                'plant_type' => 'Tomato',
                'seasonal_prevalence' => json_encode(['Spring' => 'Moderate', 'Summer' => 'High', 'Fall' => 'Moderate', 'Winter' => 'None']),
                'statistics' => json_encode([
                    'infection_rate' => '10-20% in susceptible tomato plants',
                    'yield_impact' => '5-10% reduction in tomato production',
                    'treatment_success_rate' => '70-90% with proper integrated management',
                    'common_regions' => ['Northeast US', 'Midwest US', 'Western Europe']
                ]),
                'source_url' => 'https://extension.umn.edu/diseases/tomato-mosaic-virus-and-tobacco-mosaic-virus',
            ],
            [
                'name' => 'Tomato___healthy',
                'description' => 'The tomato plant appears healthy with no visible signs of disease or pest damage.',
                'scientific_details' => 'Healthy tomato plants (Solanum lycopersicum) exhibit robust growth, dark green leaves, and well-developed fruit. The plant is resistant to common pests and diseases. Leaves are smooth, glossy, and free of spots or abnormal coloration. Branches are strong and free of cankers or lesions. Fruit development is uniform, with proper sizing and coloration. The root system is extensive and fibrous, with numerous root hairs for efficient nutrient uptake.',
                'treatment_suggestions' => 'Maintain consistent watering. Stake or cage plants for support. Prune suckers for indeterminate varieties. Monitor for common tomato pests.',
                'prevention_methods' => 'Practice crop rotation (3-4 year cycle). Use mulch to prevent soil splash onto leaves. Provide adequate spacing between plants (18-36 inches). Water at soil level rather than overhead. Apply balanced fertilizer based on soil test results. Remove lower leaves that touch the soil. Monitor regularly for early signs of common diseases.',
                'required_tools' => 'Tomato cages or stakes, pruning shears, mulch, drip irrigation or soaker hoses, balanced fertilizer, soil testing kit.',
                'environmental_factors' => 'Prefers full sun (6-8 hours daily), well-drained soil with pH 6.0-6.8, consistent moisture (1-2 inches weekly), and temperatures between 65-85°F (18-29°C) for optimal growth and fruit production.',
                'severity_level' => 'None',
                'average_treatment_time' => 0.0,
                'plant_type' => 'Tomato',
                'seasonal_prevalence' => json_encode(['Spring' => 'N/A', 'Summer' => 'N/A', 'Fall' => 'N/A', 'Winter' => 'N/A']),
                'statistics' => json_encode([
                    'productivity' => '10-30 pounds per plant for indeterminate varieties',
                    'growth_rate' => 'From seedling to first harvest in 60-100 days depending on variety',
                    'pollination' => 'Self-pollinating, enhanced by wind or mechanical vibration',
                    'common_varieties' => ['Roma', 'Beefsteak', 'Cherry', 'Heirloom', 'Determinate', 'Indeterminate']
                ]),
                'source_url' => null,
            ],
        ];

        foreach ($diseases as $disease) {
            Disease::updateOrCreate(['name' => $disease['name']], $disease);
        }
        
        // For any diseases that weren't explicitly defined above but exist in the CLASS_NAMES list,
        // ensure they have at least basic information
        $classNames = [
            'Apple___Apple_scab', 'Apple___Black_rot', 'Apple___Cedar_apple_rust', 'Apple___healthy',
            'Blueberry___healthy', 'Cherry_(including_sour)___Powdery_mildew', 'Cherry_(including_sour)___healthy',
            'Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot', 'Corn_(maize)___Common_rust_',
            'Corn_(maize)___Northern_Leaf_Blight', 'Corn_(maize)___healthy', 'Grape___Black_rot',
            'Grape___Esca_(Black_Measles)', 'Grape___Leaf_blight_(Isariopsis_Leaf_Spot)', 'Grape___healthy',
            'Orange___Haunglongbing_(Citrus_greening)', 'Peach___Bacterial_spot', 'Peach___healthy',
            'Pepper,_bell___Bacterial_spot', 'Pepper,_bell___healthy', 'Potato___Early_blight',
            'Potato___Late_blight', 'Potato___healthy', 'Raspberry___healthy', 'Soybean___healthy',
            'Squash___Powdery_mildew', 'Strawberry___Leaf_scorch', 'Strawberry___healthy',
            'Tomato___Bacterial_spot', 'Tomato___Early_blight', 'Tomato___Late_blight', 'Tomato___Leaf_Mold',
            'Tomato___Septoria_leaf_spot', 'Tomato___Spider_mites Two-spotted_spider_mite',
            'Tomato___Target_Spot', 'Tomato___Tomato_Yellow_Leaf_Curl_Virus', 'Tomato___Tomato_mosaic_virus',
            'Tomato___healthy'
        ];
        
        foreach ($classNames as $className) {
            $disease = Disease::where('name', $className)->first();
            
            if (!$disease) {
                // Extract plant type and condition
                $parts = explode('___', $className);
                $plantType = str_replace('_', ' ', $parts[0]);
                $condition = isset($parts[1]) ? str_replace('_', ' ', $parts[1]) : '';
                $isHealthy = str_contains(strtolower($className), 'healthy');
                
                // Create basic disease entry
                Disease::create([
                    'name' => $className,
                    'description' => $isHealthy 
                        ? "The {$plantType} plant appears healthy with no visible signs of disease or pest damage."
                        : "A disease affecting {$plantType} plants, characterized by {$condition}.",
                    'treatment_suggestions' => $isHealthy
                        ? "Continue regular maintenance and monitoring practices."
                        : "Consult a plant specialist for proper diagnosis and treatment options.",
                    'plant_type' => $plantType,
                    'severity_level' => $isHealthy ? 'None' : 'Unknown',
                ]);
            }
        }
    }
}